language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t andrewborges/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run andrewborges/react-test npm test -- --coverage

after_success:
  - docker build -t andrewborges/multi-client ./client
  - docker build -t andrewborges/multi-nginx ./nginx
  - docker build -t andrewborges/multi-server ./server
  - docker build -t andrewborges/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push andrewborges/multi-client
  - docker push andrewborges/multi-nginx
  - docker push andrewborges/multi-server
  - docker push andrewborges/multi-worker
